Fix: `make terraform` broken with STS credentials
Regression from 3427bfd4011df43e06ad928f37c3cda4799abf64.

```
Error: Error refreshing state: 1 error(s) occurred:

* provider.aws.us-east-1: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider
```