Fix: `make terraform` broken with STS credentials
Regression from a76fd122eb56343bdb4b7ac3320670ead8ea469d.

```
Error: Error refreshing state: 1 error(s) occurred:

* provider.aws.us-east-1: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider
```