Fix: `make terraform` broken with STS credentials
Regression from 889d137eae6c0370fb782f9f1f5e786a21e8f9c4.

```
Error: Error refreshing state: 1 error(s) occurred:

* provider.aws.us-east-1: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider
```