Fix: missing organism_age causes AttributeError during indexing
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/app.py", line 125, in _index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 48, in index
    for es_document in es_documents:
  File "/var/task/azul/project/hca/transformers.py", line 159, in create_documents
    contents = dict(specimens=_specimen_dict(visitor.specimens),
  File "/var/task/azul/project/hca/transformers.py", line 30, in _specimen_dict
    specimen.ancestors(bio_visitor)
  File "/var/task/azul/project/hca/metadata_api/__init__.py", line 98, in ancestors
    parent.ancestors(visitor)
  File "/var/task/azul/project/hca/metadata_api/__init__.py", line 99, in ancestors
    visitor.visit(parent)
  File "/var/task/azul/project/hca/transformers.py", line 134, in visit
    b["max_organism_age_in_seconds"] = entity.organism_age_in_seconds.max
  File "/var/task/azul/project/hca/metadata_api/__init__.py", line 161, in organism_age_in_seconds
    return AgeRange(self.organism_age, self.organism_age_unit)
  File "/var/task/azul/project/hca/metadata_api/__init__.py", line 571, in __init__
    age = [s.strip() for s in age.split("-")]
AttributeError: 'NoneType' object has no attribute 'split'