Fix: staging subscription query
Regression from 566e19ec75eb8d86b4c0484656deb71b998317a4

Fixes

```
Traceback (most recent call last):
  File "scripts/subscribe.py", line 38, in <module>
    main(sys.argv[1:])
  File "scripts/subscribe.py", line 32, in main
    subscription.manage_subscriptions(dss_client, subscribe=options.subscribe)
  File "/builds/azul/azul/src/azul/subscription.py", line 25, in manage_subscriptions
    for query, path in [(plugin.dss_subscription_query(prefix), '/'),
  File "/builds/azul/azul/src/azul/project/hca/__init__.py", line 80, in dss_subscription_query
    ] if config.dss_endpoint == "https://dss.staging.data.humancellatlas.org/v1" else [
TypeError: unhashable type: 'dict'
Makefile:15: recipe for target 'subscribe' failed
```