Fix: Worker fails due to read-only file system
OSError: [Errno 30] Read-only file system: '/home/sbx_user1068'

Regression from 215f909481abfef849d4863ad8e4fda28695156a