Fix: Worker fails due to read-only file system
OSError: [Errno 30] Read-only file system: '/home/sbx_user1068'

Regression from e7f3842f00d7973b97335d168148524f292c26c5