Fix: freezing and sorting of JSON objects with None values
```
======================================================================
ERROR: test_indexing (indexer.test_hca_indexer.TestHCAIndexer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/DataBiosphere/azul/test/indexer/test_hca_indexer.py", line 66, in test_indexing
    self.assertElasticsearchResultsEqual(expected_hits, hits)
  File "/home/travis/build/DataBiosphere/azul/test/es_test_case.py", line 59, in assertElasticsearchResultsEqual
    self.assertEqual(sort_frozen(freeze(first)), sort_frozen(freeze(second)))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 96, in sort_frozen
    return tuple(chain((v for v in x if v is None), sorted(sort_frozen(v) for v in x if v is not None)))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 96, in <genexpr>
    return tuple(chain((v for v in x if v is None), sorted(sort_frozen(v) for v in x if v is not None)))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 94, in sort_frozen
    return tuple(sorted((k, sort_frozen(v)) for k, v in x.items()))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 94, in <genexpr>
    return tuple(sorted((k, sort_frozen(v)) for k, v in x.items()))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 94, in sort_frozen
    return tuple(sorted((k, sort_frozen(v)) for k, v in x.items()))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 94, in <genexpr>
    return tuple(sorted((k, sort_frozen(v)) for k, v in x.items()))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 94, in sort_frozen
    return tuple(sorted((k, sort_frozen(v)) for k, v in x.items()))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 94, in <genexpr>
    return tuple(sorted((k, sort_frozen(v)) for k, v in x.items()))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 96, in sort_frozen
    return tuple(chain((v for v in x if v is None), sorted(sort_frozen(v) for v in x if v is not None)))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 96, in <genexpr>
    return tuple(chain((v for v in x if v is None), sorted(sort_frozen(v) for v in x if v is not None)))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 94, in sort_frozen
    return tuple(sorted((k, sort_frozen(v)) for k, v in x.items()))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 94, in <genexpr>
    return tuple(sorted((k, sort_frozen(v)) for k, v in x.items()))
  File "/home/travis/build/DataBiosphere/azul/src/azul/json_freeze.py", line 96, in sort_frozen
    return tuple(chain((v for v in x if v is None), sorted(sort_frozen(v) for v in x if v is not None)))
TypeError: '<' not supported between instances of 'NoneType' and 'bool'

```