Fix: Handle missing specimen fields
They can be absent when a biomaterial of a certain type is missing from lineage.

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/chalice/app.py", line 659, in _get_view_function_response
    response = view_function(**function_args)
  File "/Users/hannes/workspace/hca/azul/lambdas/service/app.py", line 208, in get_specimen_data
    index="AZUL_SPECIMEN_INDEX")
  File "/Users/hannes/workspace/hca/azul/src/azul/service/responseobjects/elastic_request_builder.py", line 526, in transform_request
    facets)
  File "/Users/hannes/workspace/hca/azul/src/azul/service/responseobjects/hca_response_v5.py", line 524, in __init__
    KeywordSearchResponse.__init__(self, hits)
  File "/Users/hannes/workspace/hca/azul/src/azul/service/responseobjects/hca_response_v5.py", line 450, in __init__
    self.map_entries(x) for x in hits], 'pagination': None}
  File "/Users/hannes/workspace/hca/azul/src/azul/service/responseobjects/hca_response_v5.py", line 450, in <listcomp>
    self.map_entries(x) for x in hits], 'pagination': None}
  File "/Users/hannes/workspace/hca/azul/src/azul/service/responseobjects/hca_response_v5.py", line 433, in map_entries
    specimens=self.make_specimens(entry),
  File "/Users/hannes/workspace/hca/azul/src/azul/service/responseobjects/hca_response_v5.py", line 411, in make_specimens
    translated_specimen[key] = [] if value is None else list(set(filter(None, value)))
TypeError: 'NoneType' object is not iterable