Fix: Worker fails due to read-only file system
OSError: [Errno 30] Read-only file system: '/home/sbx_user1068'

Regression from d7c6dd6a3699bad5c9ee960d79b6c6b229d73931