Remove defective snapshot
Contribution lambda fails due to empty array in part_of_dataset_id column of a biosample row

[WARNING]	2024-01-28T11:05:38.403Z	749604da-29f8-57ee-a041-5aea1ed5f835	azul.indexer.index_controller	Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': '98bc1093-7f8b-482c-accb-711b7d396689', 'bundle_fqid': {'uuid': '668c0777-0059-a953-a1c4-2ead9cc57417', 'version': '2022-06-01T00:00:00.000000Z', 'source': {'id': '757824d3-599f-4fab-985d-9ed847d06a62', 'spec': 'tdr:datarepo-10613413:snapshot/ANVIL_CCDG_Baylor_CVD_AFib_BioVU_WGS_20221110_ANV5_202304241855:66/0'}, 'entity_type': 'biosample'}}, 'catalog': 'anvil4-it'}.

Traceback (most recent call last):

  File "/opt/python/more_itertools/more.py", line 539, in one

    first_value = next(it)

                  ^^^^^^^^

StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/var/task/azul/indexer/index_controller.py", line 180, in contribute

    contributions, replicas = self.transform(catalog, notification, delete)

                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/var/task/azul/indexer/index_controller.py", line 228, in transform

    bundle = service.fetch_bundle(catalog, bundle_fqid)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/var/task/azul/indexer/index_service.py", line 193, in fetch_bundle

    return plugin.fetch_bundle(bundle_fqid)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/var/task/azul/plugins/repository/tdr.py", line 212, in fetch_bundle

    bundle = self._emulate_bundle(bundle_fqid)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/var/task/azul/plugins/repository/tdr_anvil/__init__.py", line 288, in _emulate_bundle

    return self._primary_bundle(bundle_fqid)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/var/task/azul/plugins/repository/tdr_anvil/__init__.py", line 311, in _primary_bundle

    new_links = method(source.spec, self._consolidate_by_type(frontier))

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/var/task/azul/plugins/repository/tdr_anvil/__init__.py", line 438, in _follow_upstream

    self._upstream_from_biosamples(source, entities['biosample']),

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/var/task/azul/plugins/repository/tdr_anvil/__init__.py", line 493, in _upstream_from_biosamples

    key=one(row['part_of_dataset_id']))}))

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/python/more_itertools/more.py", line 541, in one

    raise (

ValueError: too few items in iterable (expected 1)